Modifications to Estimator::CostForce + minor fixes
deepmind/mujoco_mpc pull request #126
Opened 2023-06-15 20:55 UTC by thowell

Modifies `Estimator::CostForce` to consider position and rotational components of forces resulting from free joints. 
Minor fix to initialization of `norm_parameters_force_`.

2023-06-15 21:01 UTC, erez-tom commented on grpc/estimator_service.cc
> -#include <cstring>
This change to the header order will upset the internal linter.  Can you please undo it, and perhaps more deeply we should figure out how to alter the style spec on your side so this doesn't happen again...

2023-06-15 21:05 UTC, erez-tom requested changes
only the header order is blocking, the other comment is just a question.

2023-06-15 21:21 UTC, thowell commented on mjpc/estimators/estimator.cc
> +  dim_sensor_ = model->nsensordata;  // TODO(taylor): grab from xml
My thinking is that if we want to have a task xml that specifies both a planner and estimator, we will need to figure out which sensors are actually sensors and not custom costs for residual terms. 

If we always use a separate xml for the estimator then we can directly grab the correct dimensions for the model.

2023-06-16 06:10 UTC, erez-tom commented on grpc/estimator_service.cc
> -#include <cstring>
Resolving so I can merge, but I'll have to manually undo this internally, so we should find a way to make sure it doesn't happen routinely.

2023-06-16 06:11 UTC, erez-tom approved these changes

2023-06-16 06:11 UTC, merged